name: Backend CI

on:
  push:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:cov

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests (with an existing testing DB)
        run: npm run test:e2e

  docker:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    needs: integration-test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DockerHubUsername }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Backend/Dockerfile
          push: true
          tags: ${{ secrets.DockerHubUsername }}/backend:latest

      - name: Smoke-test container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DockerHubUsername }}/backend:latest
          run: echo "running the docker image for testing purposes"
